@startuml Expressions
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Expression {
    type: Type
}

class IntLiteral {
    value: int
}

class DoubleLiteral {
    value: double
}

class CharLiteral {
    character: char
}

class Variable {
    name: String
    definition: Definition
}

class AritmeticOperation {
    operator: String
    leftExpression: Expression
    rightExpression: Expression
    ' Deben de poder ser evaluables
}

class Invocation implements Expression {
    argumentos: List<Expression>
}

class Cast {
    castType: Type
    exp: Expression
}

ASTNode <|-- Expression
Expression <|.. IntLiteral
Expression <|.. DoubleLiteral
Expression <|.. CharLiteral
Expression <|.. Variable
Expression <|.. AritmeticOperation
AritmeticOperation o-- "2" Expression
Expression <|.. Cast

@enduml
