@startuml Program
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

class Program

interface Definition {
}

abstract class AbstractDefinition implements Definition {
    name: String
    type: Type
}


class VarDefinition extends AbstractDefinition {
    name: String

}

class FunctionDefinition extends AbstractDefinition {
    name: String
    varDefinitions: List<VarDefinition>
    statements: List<Statement>
}


ASTNode <|.. Program
Program o-- "0..*" Definition



@enduml
