@startuml Program
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

class Program

interface Definition {
    type: Type
}

class VarDefinition implements Definition {
    name: String

}

class FunctionDefinition implements Definition {
    name: String
    varDefinitions: List<VarDefinition>
    statements: List<Statement>
    type: FuncType
}


ASTNode <|.. Program
Program o-- "0..*" Definition



@enduml
