@startuml Statements
skinparam style strictuml
skinparam monochrome true


interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Statement

class If {
    condition: Expression
    ifBody: List<Statement>
    elseBody: List<Statement>
}

class Assignment {
    leftExpression: Expression
    rightExpression: Expression
    ' Deben de poder ser evaluables
}

class Write {
    expresion: Expression
}

class Read {
    expresion: Expression
}

class While {
    condition: Expression
    body: List<Statement>
}

class Return {
    returnExpresion: Expression
}

class Invocation {
    argumentos: List<Statement>
}

ASTNode <|-- Statement
Statement <|.. If
Statement <|.. Assignment
Statement <|.. Write
Statement <|.. Read
Statement <|.. While
Statement <|.. Return
Statement <|.. Invocation
If o-- "1" Expression
If o-- "0..n" Statement


@enduml
