@startuml Types
skinparam style strictuml
skinparam monochrome true

interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Type

ASTNode <|-- Type

class IntType

Type <|.. IntType

class DoubleType

Type <|.. DoubleType

class CharType

Type <|.. CharType

class Array {
    size: int
    type: Type
}

Type <|.. Array

class Structs {
    fields: List<StructFields>
}

class StructFields implements Type {}

Type <|.. Structs

class FuncType {
    params: VarDefinition
    returnType: Type
}

Type <|.. FuncType

class Void {

}

Type <|.. Void

@enduml
