@startuml Types
skinparam style strictuml
skinparam monochrome true

interface ASTNode {
    getLine(): int
    getColumn(): int
}

interface Type

ASTNode <|-- Type

abstract AbstractType

Type <|.. AbstractType

class IntType

AbstractType <|.. IntType

class DoubleType

AbstractType <|.. DoubleType

class CharType

AbstractType <|.. CharType

class Array {
    size: int
    type: Type
}

AbstractType <|.. Array

class Struct {
    fields: List<StructFields>
}

Struct  o-- "0.*" StructFields

class StructFields implements AbstractType {
    name: String
    type: Type
}

AbstractType <|.. Struct

class FuncType {
    params: VarDefinition
    returnType: Type
}

AbstractType <|.. FuncType

class VoidType {

}

AbstractType <|.. VoidType

@enduml
